### PR TITLE
Vue3 upgrade

### PR DESCRIPTION
**Pull request by chillu**
* Upgraded to Vue 3, it's been stable for a while now (at v3.2) although it's not the "default" on vuejs.org yet. Note that I didn't use [@vue/compat](https://v3.vuejs.org/guide/migration/migration-build.html), but rather fixed the handful of deprecation notices. They've got an interesting upgrade path with feature flags, would've been cool to do that in a parallel universe for the CMS 4.x upgrade :D 
 * Update `vue-apollo` to `3@beta` (not stable yet). Removed a whole lot of gunk from the direct dependencies
 * Update [v-model usage](https://v3.vuejs.org/guide/migration/v-model.html#overview). It still feels wrong to throw untyped objects around between components, and you can pass through `v-model:myPropName` now. But I couldn't make that work with the two-way binding
 * Removed stuff we're not even using (`luxon`, `subscriptions-transport-ws`)
 * Switched to a simpler loading spinner library that didn't add a giant `node-sass` dependency (which doesn't compile on my ARM Mac...). It's a different loader style
 * Fixed a few bugs from my testing, not all of them were related to the upgrade

### CODE REVIEW

**Comment by chillu** [comment]
Preview didn't work, trying to migrate away from `now.json` based config to see if that fixes things.

**Comment by chillu** [comment]
Yep, that did the trick. I 💙 Vercel pull request request previews

**Comment by chillu** [comment]
Oh, one thing I nearly missed which necessitates this removal of `now.json`: 
I've removed all kinds of apollo gunk, and part of that was the concatenation of `VUE_APP_GRAPHQL_ENDPOINT` and `VUE_APP_GRAPHQL_PATH`. The `VUE_APP_GRAPHQL_ENDPOINT` now has the full URL in it.

*CAUTION: Since I've set this up as environment vars for preview/dev/prod already, any OTHER deployment before merging this PR might break* (depending whether now.json or project env vars take precedence.

https://github.com/silverstripe/github-issue-search-client/pull/87/files#diff-84424a47bc058dcb6180c7cc0f3bef5e1a25c55a5cbda9bc3024ce7c2320df8aL13

**Comment by michalkleiner** [comment]
I see a difference of 5 issues in the untriaged tab, could that be because of what your token vs the current token can access?
Also, I can see the issue time is now added, is that intended or just a side effect of something?

Left side is this PR preview, right side is the current public version.
Screen Shot 2021-10-15 at 11 53 29 AM

**Comment by chillu** [comment]
Whohoo, thanks Max!

**Pull request merged**
