### PR TITLE
MNT Update repositories in VCS

### PR DESCRIPTION
**Pull request by GuySartorelli**
This will trigger a re-deploy of the app with the newly updated repositories list.
Don't merge until ~~https://github.com/creative-commoners/supported-modules/pull/2~~ https://github.com/silverstripe/supported-modules/pull/17 has been merged.

## Parent issue
- https://github.com/silverstripe/github-issue-search-client/issues/100

### CODE REVIEW

**Comment by maxime-rainville** [comment]
The test environment doesn't seem to be picking up the developer-docs repo ... it's not included in the GraphQL request.

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
The test environment doesn't seem to be picking up the developer-docs repo ... it's not included in the GraphQL request.

**Comment by GuySartorelli** [comment]
@maxime-rainville You didn't merge the other PR.
There are two PRs for the attached issue. This PR's description even says not to merge it until the other has been merged. :p

**Comment by GuySartorelli** [comment]
@maxime-rainville Accidentally created the other PR against creative-commoners... please merge https://github.com/silverstripe/supported-modules/pull/17 first.

**Review by maxime-rainville — APPROVED** [review]

**Pull request merged**
